[pytest]
asyncio_mode = auto
pythonpath = .
testpaths = tests
timeout = 30
timeout_method = thread
addopts =
    --cov=.
    --cov-config=.coveragerc
    --cov-report=term-missing:skip-covered
    --cov-report=html
    --cov-fail-under=75
